version: '3.8'

services:
  myapi:
    build:
      context: ./DLS_Catalog_Service_3.0
      dockerfile: Dockerfile
    ports:
      - "8080:80"
      - "8443:7026"
    depends_on:
      - mymongodb
      - myrabbitmq
    networks:
      - app-network
    environment:
      - AllowedHosts=*
      - MongoDbSettings__ConnectionString=mongodb://mymongodb:27017
      - MongoDbSettings__DatabaseName=DLS
      - RabbitMQSettings__HostName=myrabbitmq
      - RabbitMQSettings__UserName=user
      - RabbitMQSettings__Password=password

  mymongodb:
    build:
      context: .
      dockerfile: Dockerfile.mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - app-network

  myrabbitmq:
    image: rabbitmq:3-management
    volumes:
      - ./rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
    ports:
      - "15672:15672"
      - "5672:5672"
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    networks:
      - app-network

volumes:
  mongodb_data:
    driver: local

networks:
  app-network:
    driver: bridge
