version: '3.8'
services:
  myapi:
    build: ./DLS_Catalog_Service_3.0  # Updated to point to the new project directory
    ports:
      - "8080:80"    # Map host port 8080 to container port 80 (for HTTP)
      - "8443:7026"  # Map host port 8443 to container port 7026 (for HTTPS)
    depends_on:
      - mymongodb
      - myrabbitmq
    networks:
      - app-network

  mymongodb:
    image: mongo
    volumes:
      - mongodb_data:/data/db
    networks:
      - app-network
  myrabbitmq:
   image: rabbitmq:3-management
   volumes:
    - ./rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
   ports:
    - "15672:15672"
    - "5672:5672"
   environment:
     RABBITMQ_DEFAULT_USER: user
     RABBITMQ_DEFAULT_PASS: password
   networks:
      - app-network


volumes:
  mongodb_data:
    driver: local

networks:
  app-network:
    driver: bridge
