apiVersion: apps/v1
kind: Deployment
metadata:
  name: mymongodb-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mymongodb
  template:
    metadata:
      labels:
        app: mymongodb
    spec:
      containers:
      - name: mymongodb
        image: dockerytting/mymongodb:latest
        ports:
        - containerPort: 27017
        volumeMounts:
        - name: mongodb-storage
          mountPath: /data/db
      volumes:
      - name: mongodb-storage
        persistentVolumeClaim:
          claimName: mongodb-pvc
